In [6]:
import numpy as np
a = np.arange(1, 21)
print("Array:")
print(a)
print("Number of dimensions:", a.ndim)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data type:", a.dtype)

Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Number of dimensions: 1
Shape: (20,)
Size: 20
Data type: int32


In [7]:
import numpy as np
np.random.seed(0)
arr = np.random.randint(0, 51, size=(4, 5))
print("Array:")
print(arr)
print("Item size:", arr.itemsize)
print("Number of bytes:", arr.nbytes)

Array:
[[44 47  0  3  3]
 [39  9 19 21 50]
 [36 23  6 24 24]
 [12  1 38 39 23]]
Item size: 4
Number of bytes: 80


In [8]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print("Array:")
print(arr)
print("Element in row 2, column 3:", arr[1, 2])
print("Last row:", arr[-1])
print("Last column:", arr[:, -1])

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element in row 2, column 3: 7
Last row: [ 9 10 11 12]
Last column: [ 4  8 12]


In [10]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print("Array:")
print(arr)
print("Subarray:")
print(arr[0:2, 0:2])
print("Alternate columns:")
print(arr[:, ::2])
print("Reverse columns:")
print(arr[:, ::-1])

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Subarray:
[[1 2]
 [5 6]]
Alternate columns:
[[ 1  3]
 [ 5  7]
 [ 9 11]]
Reverse columns:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [14]:
import numpy as np
arr = np.arange(1, 21).reshape(4, 5)
print("Original Array:")
print(arr)
view = arr[0:3, 0:4]
view[0, 0] = 100
print("\nOriginal Array after modifying view:")
print(arr)
copy = arr[0:3, 0:4].copy()
copy[0, 0] = 200
print("\nOriginal Array after modifying copy:")
print(arr)

Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Original Array after modifying view:
[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]

Original Array after modifying copy:
[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [15]:
import numpy as np
x = np.arange(1, 13)
print("Original Array:")
print(x)
a = x.reshape(3, 4)
print("\n3x4 Matrix:")
print(a)
b = x.reshape(12, 1)
print("\nColumn Vector using reshape:")
print(b)
c = x[:, np.newaxis]
print("\nColumn Vector using newaxis:")
print(c)
print("\nBoth are identical:", np.array_equal(b, c))

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

3x4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Column Vector using reshape:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]

Column Vector using newaxis:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]

Both are identical: True


In [16]:
import numpy as np
np.random.seed(0)
a = np.random.randint(1, 10, (2, 3))
b = np.random.randint(1, 10, (2, 3))
print("Array A:")
print(a)
print("\nArray B:")
print(b)
v1 = np.vstack((a, b))
v2 = np.concatenate((a, b), axis=0)
print("\nVertical using vstack:")
print(v1)
print("\nVertical using concatenate:")
print(v2)
print("Vertical same:", np.array_equal(v1, v2))
h1 = np.hstack((a, b))
h2 = np.concatenate((a, b), axis=1)
print("\nHorizontal using hstack:")
print(h1)
print("\nHorizontal using concatenate:")
print(h2)
print("Horizontal same:", np.array_equal(h1, h2))

Array A:
[[6 1 4]
 [4 8 4]]

Array B:
[[6 3 5]
 [8 7 9]]

Vertical using vstack:
[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]]

Vertical using concatenate:
[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]]
Vertical same: True

Horizontal using hstack:
[[6 1 4 6 3 5]
 [4 8 4 8 7 9]]

Horizontal using concatenate:
[[6 1 4 6 3 5]
 [4 8 4 8 7 9]]
Horizontal same: True


In [19]:
import numpy as np
arr = np.arange(1, 16)
print("Original Array:")
print(arr)
parts = np.split(arr, 3)
print("\nPart 1:")
print(parts[0])
print("\nPart 2:")
print(parts[1])
print("\nPart 3:")
print(parts[2])

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Part 1:
[1 2 3 4 5]

Part 2:
[ 6  7  8  9 10]

Part 3:
[11 12 13 14 15]


In [20]:
import numpy as np
arr = np.arange(1, 25).reshape(6, 4)
print("Original Array:")
print(arr)
h = np.hsplit(arr, 2)
print("\nHorizontal Split:")
print(h[0])
print(h[1])
v = np.vsplit(arr, 2)
print("\nVertical Split:")
print(v[0])
print(v[1])

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Horizontal Split:
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]
 [19 20]
 [23 24]]

Vertical Split:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
